{{- if and (not .Values.tls.existingSecret) (or .Values.tls.cert .Values.tls.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" (include "hpcc-scheduler.fullname" .) }}
  labels:
    {{- include "hpcc-scheduler.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{- .Values.tls.cert | nindent 4 }}
  tls.key: |
    {{- .Values.tls.key | nindent 4 }}
{{- end }}
{{- if and (not .Values.auth.existingSecret) .Values.auth.workerToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-auth" (include "hpcc-scheduler.fullname" .) }}
  labels:
    {{- include "hpcc-scheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  WORKER_TOKEN: {{ .Values.auth.workerToken | quote }}
{{- end }}
