// Wire schema between the host-side runner (Firecracker driver) and
// the in-VM hpcc-agent. One bidirectional streaming RPC per Exec:
// the host sends a header followed by input-file chunks, the agent
// streams stdio + the result + output-file chunks back.
//
// Streaming both directions is what lets the agent avoid buffering
// whole input files in RAM (peak memory is bounded by chunk size,
// not by sum-of-sizes), and lets the runner pipe stdio out to the
// gRPC client without waiting for the whole compile.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StdioChunk_Stream int32

const (
	StdioChunk_STDOUT StdioChunk_Stream = 0
	StdioChunk_STDERR StdioChunk_Stream = 1
)

// Enum value maps for StdioChunk_Stream.
var (
	StdioChunk_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	StdioChunk_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x StdioChunk_Stream) Enum() *StdioChunk_Stream {
	p := new(StdioChunk_Stream)
	*p = x
	return p
}

func (x StdioChunk_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StdioChunk_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_agent_proto_enumTypes[0].Descriptor()
}

func (StdioChunk_Stream) Type() protoreflect.EnumType {
	return &file_agent_agent_proto_enumTypes[0]
}

func (x StdioChunk_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StdioChunk_Stream.Descriptor instead.
func (StdioChunk_Stream) EnumDescriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{4, 0}
}

// ExecClientFrame is one of: an ExecHeader (sent first, exactly
// once), or an InputFile chunk. Frames carrying an InputFile may
// arrive in any order across files — the agent demultiplexes by
// `path`. When the client half-closes the stream the agent treats
// every staged file as complete.
type ExecClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ExecClientFrame_Header
	//	*ExecClientFrame_Input
	Frame         isExecClientFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecClientFrame) Reset() {
	*x = ExecClientFrame{}
	mi := &file_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecClientFrame) ProtoMessage() {}

func (x *ExecClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecClientFrame.ProtoReflect.Descriptor instead.
func (*ExecClientFrame) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecClientFrame) GetFrame() isExecClientFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ExecClientFrame) GetHeader() *ExecHeader {
	if x != nil {
		if x, ok := x.Frame.(*ExecClientFrame_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ExecClientFrame) GetInput() *InputFile {
	if x != nil {
		if x, ok := x.Frame.(*ExecClientFrame_Input); ok {
			return x.Input
		}
	}
	return nil
}

type isExecClientFrame_Frame interface {
	isExecClientFrame_Frame()
}

type ExecClientFrame_Header struct {
	Header *ExecHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type ExecClientFrame_Input struct {
	Input *InputFile `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

func (*ExecClientFrame_Header) isExecClientFrame_Frame() {}

func (*ExecClientFrame_Input) isExecClientFrame_Frame() {}

type ExecHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-chosen identifier; surfaces in the agent's logs and the
	// staging directory name (/run/hpcc/src/<exec_id>/).
	ExecId string `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	// Fully-resolved argv. argv[0] is the binary the agent execve's;
	// /src and /out paths are already in their in-VM form.
	Argv []string `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	// Environment for the compiler process (KEY=VALUE form). Empty
	// means "inherit none" — the agent does not propagate its own env.
	Env []string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	// Working directory for the compiler, in-VM path. Empty means the
	// staging dir for this Exec.
	Cwd string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Output paths the agent should read back from
	// /run/hpcc/out/<exec_id>/ once the compiler exits, and stream as
	// OutputFile frames. Paths are relative to that staging dir.
	Outputs       []string `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecHeader) Reset() {
	*x = ExecHeader{}
	mi := &file_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecHeader) ProtoMessage() {}

func (x *ExecHeader) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecHeader.ProtoReflect.Descriptor instead.
func (*ExecHeader) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecHeader) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecHeader) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecHeader) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecHeader) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecHeader) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// InputFile is one chunk of one input file. The agent writes chunks
// in arrival order into /run/hpcc/src/<exec_id>/<path>; on `eof` it
// closes the fd. Setting `eof = true` with empty `chunk` is the
// way to materialize a zero-byte file.
type InputFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputFile) Reset() {
	*x = InputFile{}
	mi := &file_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFile) ProtoMessage() {}

func (x *InputFile) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFile.ProtoReflect.Descriptor instead.
func (*InputFile) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *InputFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InputFile) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *InputFile) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// ExecServerFrame is one of: a stdio chunk produced by the running
// compiler, the final ExecResult (sent exactly once, after the
// process exits), or an OutputFile chunk. Stdio frames may interleave
// freely; OutputFile frames only appear after ExecResult.
type ExecServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ExecServerFrame_Stdio
	//	*ExecServerFrame_Result
	//	*ExecServerFrame_Output
	Frame         isExecServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecServerFrame) Reset() {
	*x = ExecServerFrame{}
	mi := &file_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecServerFrame) ProtoMessage() {}

func (x *ExecServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecServerFrame.ProtoReflect.Descriptor instead.
func (*ExecServerFrame) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ExecServerFrame) GetFrame() isExecServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ExecServerFrame) GetStdio() *StdioChunk {
	if x != nil {
		if x, ok := x.Frame.(*ExecServerFrame_Stdio); ok {
			return x.Stdio
		}
	}
	return nil
}

func (x *ExecServerFrame) GetResult() *ExecResult {
	if x != nil {
		if x, ok := x.Frame.(*ExecServerFrame_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ExecServerFrame) GetOutput() *OutputFile {
	if x != nil {
		if x, ok := x.Frame.(*ExecServerFrame_Output); ok {
			return x.Output
		}
	}
	return nil
}

type isExecServerFrame_Frame interface {
	isExecServerFrame_Frame()
}

type ExecServerFrame_Stdio struct {
	Stdio *StdioChunk `protobuf:"bytes,1,opt,name=stdio,proto3,oneof"`
}

type ExecServerFrame_Result struct {
	Result *ExecResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ExecServerFrame_Output struct {
	Output *OutputFile `protobuf:"bytes,3,opt,name=output,proto3,oneof"`
}

func (*ExecServerFrame_Stdio) isExecServerFrame_Frame() {}

func (*ExecServerFrame_Result) isExecServerFrame_Frame() {}

func (*ExecServerFrame_Output) isExecServerFrame_Frame() {}

type StdioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        StdioChunk_Stream      `protobuf:"varint,1,opt,name=stream,proto3,enum=hpcc.agent.v1.StdioChunk_Stream" json:"stream,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdioChunk) Reset() {
	*x = StdioChunk{}
	mi := &file_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioChunk) ProtoMessage() {}

func (x *StdioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioChunk.ProtoReflect.Descriptor instead.
func (*StdioChunk) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StdioChunk) GetStream() StdioChunk_Stream {
	if x != nil {
		return x.Stream
	}
	return StdioChunk_STDOUT
}

func (x *StdioChunk) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type ExecResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process exit code. Negative values are reserved for runner-
	// synthesized failures (signal kills, agent-side errors).
	ExitCode      int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResult) Reset() {
	*x = ExecResult{}
	mi := &file_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResult) ProtoMessage() {}

func (x *ExecResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResult.ProtoReflect.Descriptor instead.
func (*ExecResult) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExecResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type OutputFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputFile) Reset() {
	*x = OutputFile{}
	mi := &file_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputFile) ProtoMessage() {}

func (x *OutputFile) ProtoReflect() protoreflect.Message {
	mi := &file_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputFile.ProtoReflect.Descriptor instead.
func (*OutputFile) Descriptor() ([]byte, []int) {
	return file_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *OutputFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OutputFile) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *OutputFile) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_agent_agent_proto protoreflect.FileDescriptor

const file_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x11agent/agent.proto\x12\rhpcc.agent.v1\"\x81\x01\n" +
	"\x0fExecClientFrame\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x19.hpcc.agent.v1.ExecHeaderH\x00R\x06header\x120\n" +
	"\x05input\x18\x02 \x01(\v2\x18.hpcc.agent.v1.InputFileH\x00R\x05inputB\a\n" +
	"\x05frame\"w\n" +
	"\n" +
	"ExecHeader\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x18\n" +
	"\aoutputs\x18\x05 \x03(\tR\aoutputs\"G\n" +
	"\tInputFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"\xb7\x01\n" +
	"\x0fExecServerFrame\x121\n" +
	"\x05stdio\x18\x01 \x01(\v2\x19.hpcc.agent.v1.StdioChunkH\x00R\x05stdio\x123\n" +
	"\x06result\x18\x02 \x01(\v2\x19.hpcc.agent.v1.ExecResultH\x00R\x06result\x123\n" +
	"\x06output\x18\x03 \x01(\v2\x19.hpcc.agent.v1.OutputFileH\x00R\x06outputB\a\n" +
	"\x05frame\"~\n" +
	"\n" +
	"StdioChunk\x128\n" +
	"\x06stream\x18\x01 \x01(\x0e2 .hpcc.agent.v1.StdioChunk.StreamR\x06stream\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\fR\x05bytes\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\")\n" +
	"\n" +
	"ExecResult\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"H\n" +
	"\n" +
	"OutputFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof2Z\n" +
	"\fAgentService\x12J\n" +
	"\x04Exec\x12\x1e.hpcc.agent.v1.ExecClientFrame\x1a\x1e.hpcc.agent.v1.ExecServerFrame(\x010\x01B*Z(github.com/aarani/hpcc/proto/agent;agentb\x06proto3"

var (
	file_agent_agent_proto_rawDescOnce sync.Once
	file_agent_agent_proto_rawDescData []byte
)

func file_agent_agent_proto_rawDescGZIP() []byte {
	file_agent_agent_proto_rawDescOnce.Do(func() {
		file_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)))
	})
	return file_agent_agent_proto_rawDescData
}

var file_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_agent_proto_goTypes = []any{
	(StdioChunk_Stream)(0),  // 0: hpcc.agent.v1.StdioChunk.Stream
	(*ExecClientFrame)(nil), // 1: hpcc.agent.v1.ExecClientFrame
	(*ExecHeader)(nil),      // 2: hpcc.agent.v1.ExecHeader
	(*InputFile)(nil),       // 3: hpcc.agent.v1.InputFile
	(*ExecServerFrame)(nil), // 4: hpcc.agent.v1.ExecServerFrame
	(*StdioChunk)(nil),      // 5: hpcc.agent.v1.StdioChunk
	(*ExecResult)(nil),      // 6: hpcc.agent.v1.ExecResult
	(*OutputFile)(nil),      // 7: hpcc.agent.v1.OutputFile
}
var file_agent_agent_proto_depIdxs = []int32{
	2, // 0: hpcc.agent.v1.ExecClientFrame.header:type_name -> hpcc.agent.v1.ExecHeader
	3, // 1: hpcc.agent.v1.ExecClientFrame.input:type_name -> hpcc.agent.v1.InputFile
	5, // 2: hpcc.agent.v1.ExecServerFrame.stdio:type_name -> hpcc.agent.v1.StdioChunk
	6, // 3: hpcc.agent.v1.ExecServerFrame.result:type_name -> hpcc.agent.v1.ExecResult
	7, // 4: hpcc.agent.v1.ExecServerFrame.output:type_name -> hpcc.agent.v1.OutputFile
	0, // 5: hpcc.agent.v1.StdioChunk.stream:type_name -> hpcc.agent.v1.StdioChunk.Stream
	1, // 6: hpcc.agent.v1.AgentService.Exec:input_type -> hpcc.agent.v1.ExecClientFrame
	4, // 7: hpcc.agent.v1.AgentService.Exec:output_type -> hpcc.agent.v1.ExecServerFrame
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_agent_agent_proto_init() }
func file_agent_agent_proto_init() {
	if File_agent_agent_proto != nil {
		return
	}
	file_agent_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecClientFrame_Header)(nil),
		(*ExecClientFrame_Input)(nil),
	}
	file_agent_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*ExecServerFrame_Stdio)(nil),
		(*ExecServerFrame_Result)(nil),
		(*ExecServerFrame_Output)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_agent_proto_rawDesc), len(file_agent_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_agent_proto_goTypes,
		DependencyIndexes: file_agent_agent_proto_depIdxs,
		EnumInfos:         file_agent_agent_proto_enumTypes,
		MessageInfos:      file_agent_agent_proto_msgTypes,
	}.Build()
	File_agent_agent_proto = out.File
	file_agent_agent_proto_goTypes = nil
	file_agent_agent_proto_depIdxs = nil
}
